<?php
  if(!defined('BASEPATH')) exit('direct access invalid');
  class Home extends CI_Controller
  {
      function __construct()
      {
          parent::__construct();
            
            $this->load->model('home_model');
      }

      function index()
      {
          $this->_siteInfo();
          $this->_frontportion();
          $this->_about_golfkeeper_app_slide();
          $this->_feature();
          $this->_storesusbscription();
          $this->template->add_js('asset/js/custom-js/front.js');
          $this->template->render();
      }//$this->template->write('content',$heading);
      
      function _frontportion()
      {
          $this->template->write_view('front','home/front_section');
      }

      function _about_golfkeeper_app_slide()
      {
          $about_slidecat_id = 2;
          $about_app_page_id = 6;
          $data['slides']=$this->home_model->getSlide($about_slidecat_id);
          $data['about_app']=$this->home_model->getSinglePageInfo($about_app_page_id);
          $this->template->write_view('slide','home/about_appslider',$data);
      }

      function _feature()
      {
          $createpage_id = 3;
          $managepage_id =4;
          $sharepage_id = 5;
          $data['create']=$this->home_model->getSinglePageInfo($createpage_id);
          $data['manage']=$this->home_model->getSinglePageInfo($managepage_id);
          $data['share']=$this->home_model->getSinglePageInfo($sharepage_id);
          $this->template->write_view('feature','feature/golfapp_features',$data);
      }

      function _storesusbscription()
      {
          $data['link']=$this->home_model->getSocialLinks(1);
          $this->template->write_view('store_subscription','home/store_subscription',$data);
      }

      function _siteInfo(){
        $seopage_id = 1;
        $data['site_info']=$this->home_model->getSeoPageInfo($seopage_id);
        $this->template->write_view('site_info','inc/siteinfo',$data);
      }

      function subscribe(){
          $email = trim($this->input->post('email'));
          require_once(APPPATH.'libraries/mailchimp.php');
          $MailChimp = new \drewm\Mailchimp($this->config->item('api_key'));
          $results = $MailChimp->call("lists/subscribe", array(
                "id"=> $this->config->item('golfkeeper_list_id'), // required, the list id to connect to. Get by calling lists/list()
                "email"=> array(
                  "email"=>$email,
                  "euid"=>"123456",/*euid and leid is provided static bcoz its just a formality. They are generated by mailchimp*/
                  "leid"=>"125",
                ),
              ));
          echo json_encode($results);
      }

      function findColorHexValue($color){
          $color_hex_value = $this->home_model->get_hex_value($color);
          return $color_hex_value['id'];
      }
      
      // function index(){
      //     require_once(APPPATH.'libraries/reader.php');
      //     ini_set('memory_limit', '-1');
      //     // $file=APPPATH.'libraries/test_int_full_database.xls';
      //     $file=APPPATH.'libraries/intl_fulldatabase_color_updated.xls';
      //     $connection=new Spreadsheet_Excel_Reader(); // our main object
      //     $connection->read($file);
      //     $startrow_club = 2;
      //     $endrow_club = 20;

      //     $startrow_courses = 2;
      //     $endrow_courses = 29;

      //     $startrow_tee = 2;
      //     $endrow_tee = 100;

      //     // $endrow_club = $connection->sheets[0]['numRows'];
      //     // $cols_club = $connection->sheets[0]['numCols'];

      //     // $startrow=2;
      //     // $endrow=4;
      //     // $col1=3;
      //     $counter = 0; 
      //     $course_info = array();
      //     for($i=$startrow_club;$i<=$endrow_club;$i++){ // we read row to row
      //           $club_id = trim($connection->sheets[0]["cells"][$i][1]);
      //           $club_total_holes = trim($connection->sheets[0]["cells"][$i][4]);
      //           $club_address = trim($connection->sheets[0]["cells"][$i][5]);
      //           $club_lat = trim($connection->sheets[0]["cells"][$i][13]);
      //           $club_long = trim($connection->sheets[0]["cells"][$i][14]);


      //           for($j=$startrow_courses; $j<=$endrow_courses; $j++){
      //             //Starting of courses sheet
      //             $course_id = $connection->sheets[1]["cells"][$j][1];
      //             $course_club_id = $connection->sheets[1]["cells"][$j][2];
      //             $course_name = $connection->sheets[1]["cells"][$j][3];
      //             $course_hole = $connection->sheets[1]["cells"][$j][4];
      //             $course_par = $connection->sheets[1]["cells"][$j][5];

      //             // $data_cs_info = array(
      //             //         'coursename' => $course_name, 
      //             //         'courseaddress' => $club_address, 
      //             //         'latitude' => $club_lat, 
      //             //         'longitude' => $club_long, 
      //             //         'totalhole' => $course_hole, 
      //             //         'image' => 'images/golfcourse/golfavatar.png', 
      //             //         'state' => 1
      //             //       );
      //             // $insert_course_id = $this->home_model->insertData('coursetable',$data_cs_info);

      //             $tee_info = array();
      //               if($course_hole <= 18){
      //                 for($k=$startrow_tee; $k<=$endrow_tee; $k++){
      //                     //Starting of tee sets
      //                     $tee_course_id = $connection->sheets[2]["cells"][$k][2];
      //                     $tee_name = $connection->sheets[2]["cells"][$k][3];
      //                     $tee_color = $this->findColorHexValue($connection->sheets[2]["cells"][$k][4]);
      //                     $tee_sloperating = $connection->sheets[2]["cells"][$k][6];
      //                     $tee_courserating = $connection->sheets[2]["cells"][$k][7];

      //                     // $data_tee_info = array(
      //                     //       'course_id' => $insert_course_id, 
      //                     //       'teename' => $tee_name, 
      //                     //       'teecolor' => $tee_color, 
      //                     //       'sloperating' => $tee_sloperating, 
      //                     //       'courserating' => $tee_courserating, 
      //                     //       'state' => 1,
      //                     //     );
      //                     // $insert_teeset_id = $this->home_model->insertData('teeset',$data_tee_info);
      //                     $hole_info = array();
      //                     if($course_id == $tee_course_id){
      //                       for($m=1; $m<=$course_hole; $m++){
      //                           //Starting of Hole sets
      //                           $hole_no = $m;
      //                           $hole_marker_distance = $connection->sheets[2]["cells"][$k][7 + $m];
      //                           $hole_par = $connection->sheets[2]["cells"][$k][26 + $m];
      //                           $hole_handicap = $connection->sheets[2]["cells"][$k][44 + $m];

      //                           // $data_hole_info = array(
      //                           //   'teeset_id' => $insert_teeset_id, 
      //                           //   'holeno' => $hole_no, 
      //                           //   'par' => $hole_par, 
      //                           //   'handicap' => $hole_handicap, 
      //                           //   'marker_distance' => $hole_marker_distance, 
      //                           //   'state' => 1,
      //                           // );
      //                           // $this->home_model->insertData('hole',$data_hole_info);

      //                           $hole_info[] = array(
      //                             'holeno' => $hole_no, 
      //                             'par' => $hole_par, 
      //                             'handicap' => $hole_handicap, 
      //                             'marker_distance' => $hole_marker_distance, 
      //                             'state' => 1,
      //                           );
      //                         }

      //                         $tee_info[] = array(
      //                           'course_id' => $tee_course_id, 
      //                           'teename' => $tee_name, 
      //                           'teecolor' => $tee_color, 
      //                           'sloperating' => $tee_sloperating, 
      //                           'courserating' => $tee_courserating, 
      //                           'course_id' => $tee_course_id, 
      //                           'state' => 1,
      //                           'hole_info_arr' => $hole_info
      //                         );
      //                     }
      //                 }
      //             }
                    
      //               if($club_id == $course_club_id && $course_hole <= 18 && !empty($tee_info)){
      //                   $course_info[] = array(
      //                     'coursename' => $course_name, 
      //                     'courseaddress' => $club_address, 
      //                     'latitude' => $club_lat, 
      //                     'longitude' => $club_long, 
      //                     'totalhole' => $course_hole,
      //                     'purchase_id' => 'com.view9.'.$course_id,
      //                     'image' => 'images/golfcourse/golfavatar.png', 
      //                     'state' => 1, 
      //                     'tee_info_arr' => $tee_info, 
      //                   );
      //               }
      //           }
      //     }

      //     $counter = 0;
      //     if($course_info){
      //       foreach($course_info as $cs){
      //           $counter++;
      //           $data_cs_info = array(
      //                       'coursename' => $cs['coursename'], 
      //                       'courseaddress' => $cs['courseaddress'], 
      //                       'latitude' => $cs['latitude'], 
      //                       'longitude' => $cs['longitude'], 
      //                       'totalhole' => $cs['totalhole'], 
      //                       'purchase_id' => 'com.view9.'.$course_id,
      //                       'image' => 'images/golfcourse/golfavatar.png', 
      //                       'state' => 1
      //                     );
      //             $insert_course_id = $this->home_model->insertData('coursetable',$data_cs_info);
      //             foreach($cs['tee_info_arr'] as $te){
      //                 $data_tee_info = array(
      //                         'course_id' => $insert_course_id, 
      //                         'teename' => $te['teename'], 
      //                         'teecolor' => $te['teecolor'], 
      //                         'sloperating' => $te['sloperating'], 
      //                         'courserating' => $te['courserating'], 
      //                         'state' => 1,
      //                       );
      //                   $insert_teeset_id = $this->home_model->insertData('teeset',$data_tee_info);

      //                   foreach($te['hole_info_arr'] as $ho){
      //                       $data_hole_info = array(
      //                         'teeset_id' => $insert_teeset_id, 
      //                         'holeno' => $ho['holeno'], 
      //                         'par' => $ho['par'], 
      //                         'handicap' => $ho['handicap'], 
      //                         'marker_distance' => $ho['marker_distance'], 
      //                         'state' => 1,
      //                       );
      //                       $this->home_model->insertData('hole',$data_hole_info);
      //                   }
      //             }
      //       }
      //     }
      // }
      // 
      
      /*New code for uploading into database*/
      // function index(){
      //     require_once(APPPATH.'libraries/reader.php');
      //     ini_set('memory_limit', '-1');
      //     ini_set('max_execution_time', 0);
      //     // $file=APPPATH.'libraries/test_int_full_database.xls';
      //     $file=APPPATH.'libraries/intl_fulldatabase_color_updated.xls';
      //     $connection = new Spreadsheet_Excel_Reader($file,false); // our main object
      //     $connection->read($file);
      //     $startrow_club = 2;
      //     $endrow_club = 1000;

      //     $startrow_courses = 2;
      //     $endrow_courses = 1088;

      //     $startrow_tee = 2;
      //     $endrow_tee = 1841;

      //     // $endrow_club = $connection->sheets[0]['numRows'];
      //     // $cols_club = $connection->sheets[0]['numCols'];

      //     // $startrow=2;
      //     // $endrow=4;
      //     // $col1=3;
      //     $counter = 0; 
      //     $course_info = array();
      //     for($i=$startrow_club;$i<=$endrow_club;$i++){ // we read row to row
      //           $club_id = trim($connection->sheets[0]["cells"][$i][1]);
      //           $club_total_holes = trim($connection->sheets[0]["cells"][$i][4]);
      //           $club_address = trim($connection->sheets[0]["cells"][$i][5]);
      //           $club_lat = trim($connection->sheets[0]["cells"][$i][13]);
      //           $club_long = trim($connection->sheets[0]["cells"][$i][14]);


      //           for($j=$startrow_courses; $j<=$endrow_courses; $j++){
      //             //Starting of courses sheet
      //             $course_id = $connection->sheets[1]["cells"][$j][1];
      //             $course_club_id = $connection->sheets[1]["cells"][$j][2];
      //             $course_name = $connection->sheets[1]["cells"][$j][3];
      //             $course_hole = $connection->sheets[1]["cells"][$j][4];

      //             $tee_info = array();
      //               if($course_hole <= 18){
      //                 for($k=$startrow_tee; $k<=$endrow_tee; $k++){
      //                     //Starting of tee sets
      //                     $tee_course_id = $connection->sheets[2]["cells"][$k][2];
      //                     $tee_name = $connection->sheets[2]["cells"][$k][3];
      //                     $tee_color = $this->findColorHexValue($connection->sheets[2]["cells"][$k][4]);
      //                     $tee_sloperating = $connection->sheets[2]["cells"][$k][6];
      //                     $tee_courserating = $connection->sheets[2]["cells"][$k][7];

      //                     $hole_info = array();
      //                     if($course_id == $tee_course_id){
      //                       for($m=1; $m<=$course_hole; $m++){
      //                           //Starting of Hole sets
      //                           $hole_no = $m;
      //                           $hole_marker_distance = $connection->sheets[2]["cells"][$k][7 + $m];
      //                           $hole_par = $connection->sheets[2]["cells"][$k][26 + $m];
      //                           $hole_handicap = $connection->sheets[2]["cells"][$k][44 + $m];


      //                           $hole_info[] = array(
      //                             'holeno' => $hole_no, 
      //                             'par' => $hole_par, 
      //                             'handicap' => $hole_handicap, 
      //                             'marker_distance' => $hole_marker_distance, 
      //                             'state' => 1,
      //                           );
      //                         }

      //                         $tee_info[] = array(
      //                           'course_id' => $tee_course_id, 
      //                           'teename' => $tee_name, 
      //                           'teecolor' => $tee_color, 
      //                           'sloperating' => $tee_sloperating, 
      //                           'courserating' => $tee_courserating, 
      //                           'course_id' => $tee_course_id, 
      //                           'state' => 1,
      //                           'hole_info_arr' => $hole_info
      //                         );
      //                     }
      //                 }
      //             }
                    
      //               if($club_id == $course_club_id && $course_hole <= 18 && !empty($tee_info)){
      //                   $course_info[] = array(
      //                     'coursename' => $course_name, 
      //                     'courseaddress' => $club_address, 
      //                     'latitude' => $club_lat, 
      //                     'longitude' => $club_long, 
      //                     'totalhole' => $course_hole,
      //                     'purchase_id' => 'com.view9.'.$course_id,
      //                     'image' => 'images/golfcourse/golfavatar.png', 
      //                     'state' => 1, 
      //                     'tee_info_arr' => $tee_info, 
      //                   );
      //                   $this->insertCourses($course_info);
      //                   $course_info = array();
      //               }
      //           }
      //     }

      // }

      // function insertCourses($course_info){
      //     $counter = 0;
      //     if($course_info){
      //       foreach($course_info as $cs){
      //         echo "<pre>";
      //         print_r($cs);
      //         echo '</br>';
      //           $data_cs_info = array(
      //                       'coursename' => $cs['coursename'], 
      //                       'courseaddress' => $cs['courseaddress'], 
      //                       'latitude' => $cs['latitude'], 
      //                       'longitude' => $cs['longitude'], 
      //                       'totalhole' => $cs['totalhole'], 
      //                       'purchase_id' => $cs['purchase_id'],
      //                       'image' => 'images/golfcourse/golfavatar.png', 
      //                       'state' => 1
      //                     );
      //             $insert_course_id = $this->home_model->insertData('coursetable',$data_cs_info);
      //             foreach($cs['tee_info_arr'] as $te){
      //                 $data_tee_info = array(
      //                         'course_id' => $insert_course_id, 
      //                         'teename' => $te['teename'], 
      //                         'teecolor' => $te['teecolor'], 
      //                         'sloperating' => $te['sloperating'], 
      //                         'courserating' => $te['courserating'], 
      //                         'state' => 1,
      //                       );
      //                   $insert_teeset_id = $this->home_model->insertData('teeset',$data_tee_info);

      //                   foreach($te['hole_info_arr'] as $ho){
      //                       $data_hole_info = array(
      //                         'teeset_id' => $insert_teeset_id, 
      //                         'holeno' => $ho['holeno'], 
      //                         'par' => $ho['par'], 
      //                         'handicap' => $ho['handicap'], 
      //                         'marker_distance' => $ho['marker_distance'], 
      //                         'state' => 1,
      //                       );
      //                       $this->home_model->insertData('hole',$data_hole_info);
      //                   }
      //             }
      //       }
      //     }
      //   return true;
      // }
      /*New code for uploading into database*/


      /*New code for testing uploading of only tees*/
      function excel_tees(){
          require_once(APPPATH.'libraries/reader.php');
          ini_set('memory_limit', '-1');
          ini_set('max_execution_time', 0);
          set_time_limit(0);
          // $file=APPPATH.'libraries/test_int_full_database.xls';
          $file=APPPATH.'libraries/test_tees.xls';
          $connection = new Spreadsheet_Excel_Reader(); // our main object
          $connection->read($file);
          //12918
          $startrow_tee = 2;
          $endrow_tee = 18265;
          echo '<pre>';
          for($i=$startrow_tee;$i<=$endrow_tee;$i++){ // we read row to row

                $data = array(
                  'tee_id' => (trim($connection->sheets[0]["cells"][$i][1])) ? trim($connection->sheets[0]["cells"][$i][1]) : 0, 
                  'course_id' => (trim($connection->sheets[0]["cells"][$i][2])) ? trim($connection->sheets[0]["cells"][$i][2]) : 0, 
                  'tee_name' => (trim($connection->sheets[0]["cells"][$i][3])) ? trim($connection->sheets[0]["cells"][$i][3]) : 0, 
                  'tee_color' => (trim($connection->sheets[0]["cells"][$i][4])) ? trim($connection->sheets[0]["cells"][$i][4]) : 0, 
                  'course_par_for_tee' => (trim($connection->sheets[0]["cells"][$i][5])) ? trim($connection->sheets[0]["cells"][$i][5]) : 0, 
                  'rating' => (trim($connection->sheets[0]["cells"][$i][6])) ? trim($connection->sheets[0]["cells"][$i][6]) : 0,
                  'slope' => (trim($connection->sheets[0]["cells"][$i][7])) ? trim($connection->sheets[0]["cells"][$i][7]) : 0,
                  'hole1' => (trim($connection->sheets[0]["cells"][$i][8])) ? trim($connection->sheets[0]["cells"][$i][8]) : 0,
                  'hole2' => (trim($connection->sheets[0]["cells"][$i][9])) ? trim($connection->sheets[0]["cells"][$i][9]) : 0,
                  'hole3' => (trim($connection->sheets[0]["cells"][$i][10])) ? trim($connection->sheets[0]["cells"][$i][10]) : 0,
                  'hole4' => (trim($connection->sheets[0]["cells"][$i][11])) ? trim($connection->sheets[0]["cells"][$i][11]) : 0,
                  'hole5' => (trim($connection->sheets[0]["cells"][$i][12])) ? trim($connection->sheets[0]["cells"][$i][12]) : 0,
                  'hole6' => (trim($connection->sheets[0]["cells"][$i][13])) ? trim($connection->sheets[0]["cells"][$i][13]) : 0,
                  'hole7' => (trim($connection->sheets[0]["cells"][$i][14])) ? trim($connection->sheets[0]["cells"][$i][14]) : 0,
                  'hole8' => (trim($connection->sheets[0]["cells"][$i][15])) ? trim($connection->sheets[0]["cells"][$i][15]) : 0,
                  'hole9' => (trim($connection->sheets[0]["cells"][$i][16])) ? trim($connection->sheets[0]["cells"][$i][16]) : 0,
                  'hole10' => (trim($connection->sheets[0]["cells"][$i][17])) ? trim($connection->sheets[0]["cells"][$i][17]) : 0,
                  'hole11' => (trim($connection->sheets[0]["cells"][$i][18])) ? trim($connection->sheets[0]["cells"][$i][18]) : 0,
                  'hole12' => (trim($connection->sheets[0]["cells"][$i][19])) ? trim($connection->sheets[0]["cells"][$i][19]) : 0,
                  'hole13' => (trim($connection->sheets[0]["cells"][$i][20])) ? trim($connection->sheets[0]["cells"][$i][20]) : 0,
                  'hole14' => (trim($connection->sheets[0]["cells"][$i][21])) ? trim($connection->sheets[0]["cells"][$i][21]) : 0,
                  'hole15' => (trim($connection->sheets[0]["cells"][$i][22])) ? trim($connection->sheets[0]["cells"][$i][22]) : 0,
                  'hole16' => (trim($connection->sheets[0]["cells"][$i][23])) ? trim($connection->sheets[0]["cells"][$i][23]) : 0,
                  'hole17' => (trim($connection->sheets[0]["cells"][$i][24])) ? trim($connection->sheets[0]["cells"][$i][24]) : 0,
                  'hole18' => (trim($connection->sheets[0]["cells"][$i][25])) ? trim($connection->sheets[0]["cells"][$i][25]) : 0,
                  'total_distance' => (trim($connection->sheets[0]["cells"][$i][26])) ? trim($connection->sheets[0]["cells"][$i][26]) : 0,
                  'hole1_par' => (trim($connection->sheets[0]["cells"][$i][27])) ? trim($connection->sheets[0]["cells"][$i][27]) : 0,
                  'hole2_par' => (trim($connection->sheets[0]["cells"][$i][28])) ? trim($connection->sheets[0]["cells"][$i][28]) : 0,
                  'hole3_par' => (trim($connection->sheets[0]["cells"][$i][29])) ? trim($connection->sheets[0]["cells"][$i][29]) : 0,
                  'hole4_par' => (trim($connection->sheets[0]["cells"][$i][30])) ? trim($connection->sheets[0]["cells"][$i][30]) : 0,
                  'hole5_par' => (trim($connection->sheets[0]["cells"][$i][31])) ? trim($connection->sheets[0]["cells"][$i][31]) : 0,
                  'hole6_par' => (trim($connection->sheets[0]["cells"][$i][32])) ? trim($connection->sheets[0]["cells"][$i][32]) : 0,
                  'hole7_par' => (trim($connection->sheets[0]["cells"][$i][33])) ? trim($connection->sheets[0]["cells"][$i][33]) : 0,
                  'hole8_par' => (trim($connection->sheets[0]["cells"][$i][34])) ? trim($connection->sheets[0]["cells"][$i][34]) : 0,
                  'hole9_par' => (trim($connection->sheets[0]["cells"][$i][35])) ? trim($connection->sheets[0]["cells"][$i][35]) : 0,
                  'hole10_par' => (trim($connection->sheets[0]["cells"][$i][36])) ? trim($connection->sheets[0]["cells"][$i][36]) : 0,
                  'hole11_par' => (trim($connection->sheets[0]["cells"][$i][37])) ? trim($connection->sheets[0]["cells"][$i][37]) : 0,
                  'hole12_par' => (trim($connection->sheets[0]["cells"][$i][38])) ? trim($connection->sheets[0]["cells"][$i][38]) : 0,
                  'hole13_par' => (trim($connection->sheets[0]["cells"][$i][39])) ? trim($connection->sheets[0]["cells"][$i][39]) : 0,
                  'hole14_par' => (trim($connection->sheets[0]["cells"][$i][40])) ? trim($connection->sheets[0]["cells"][$i][40]) : 0,
                  'hole15_par' => (trim($connection->sheets[0]["cells"][$i][41])) ? trim($connection->sheets[0]["cells"][$i][41]) : 0,
                  'hole16_par' => (trim($connection->sheets[0]["cells"][$i][42])) ? trim($connection->sheets[0]["cells"][$i][42]) : 0,
                  'hole17_par' => (trim($connection->sheets[0]["cells"][$i][43])) ? trim($connection->sheets[0]["cells"][$i][43]) : 0,
                  'hole18_par' => (trim($connection->sheets[0]["cells"][$i][44])) ? trim($connection->sheets[0]["cells"][$i][44]) : 0,
                  'hole1_handicap' => (trim($connection->sheets[0]["cells"][$i][45])) ? trim($connection->sheets[0]["cells"][$i][45]) : 0,
                  'hole2_handicap' => (trim($connection->sheets[0]["cells"][$i][46])) ? trim($connection->sheets[0]["cells"][$i][46]) : 0,
                  'hole3_handicap' => (trim($connection->sheets[0]["cells"][$i][47])) ? trim($connection->sheets[0]["cells"][$i][47]) : 0,
                  'hole4_handicap' => (trim($connection->sheets[0]["cells"][$i][48])) ? trim($connection->sheets[0]["cells"][$i][48]) : 0,
                  'hole5_handicap' => (trim($connection->sheets[0]["cells"][$i][49])) ? trim($connection->sheets[0]["cells"][$i][49]) : 0,
                  'hole6_handicap' => (trim($connection->sheets[0]["cells"][$i][50])) ? trim($connection->sheets[0]["cells"][$i][50]) : 0,
                  'hole7_handicap' => (trim($connection->sheets[0]["cells"][$i][51])) ? trim($connection->sheets[0]["cells"][$i][51]) : 0,
                  'hole8_handicap' => (trim($connection->sheets[0]["cells"][$i][52])) ? trim($connection->sheets[0]["cells"][$i][52]) : 0,
                  'hole9_handicap' => (trim($connection->sheets[0]["cells"][$i][53])) ? trim($connection->sheets[0]["cells"][$i][53]) : 0,
                  'hole10_handicap' => (trim($connection->sheets[0]["cells"][$i][54])) ? trim($connection->sheets[0]["cells"][$i][54]) : 0,
                  'hole11_handicap' => (trim($connection->sheets[0]["cells"][$i][55])) ? trim($connection->sheets[0]["cells"][$i][55]) : 0,
                  'hole12_handicap' => (trim($connection->sheets[0]["cells"][$i][56])) ? trim($connection->sheets[0]["cells"][$i][56]) : 0,
                  'hole13_handicap' => (trim($connection->sheets[0]["cells"][$i][57])) ? trim($connection->sheets[0]["cells"][$i][57]) : 0,
                  'hole14_handicap' => (trim($connection->sheets[0]["cells"][$i][58])) ? trim($connection->sheets[0]["cells"][$i][58]) : 0,
                  'hole15_handicap' => (trim($connection->sheets[0]["cells"][$i][59])) ? trim($connection->sheets[0]["cells"][$i][59]) : 0,
                  'hole16_handicap' => (trim($connection->sheets[0]["cells"][$i][60])) ? trim($connection->sheets[0]["cells"][$i][60]) : 0,
                  'hole17_handicap' => (trim($connection->sheets[0]["cells"][$i][61])) ? trim($connection->sheets[0]["cells"][$i][61]) : 0,
                  'hole18_handicap' => (trim($connection->sheets[0]["cells"][$i][62])) ? trim($connection->sheets[0]["cells"][$i][62]) : 0,
                );
                echo trim($connection->sheets[0]["cells"][$i][1]).'   --'.$i;
                echo '</br>';
                $this->home_model->insertData('tee_info',$data);
          }
      }
      
      
      // /*New uploading for courses*/
        function excel_courses(){
          require_once(APPPATH.'libraries/reader.php');
          ini_set('memory_limit', '-1');
          ini_set('max_execution_time', 0);
          set_time_limit(0);
          // $file=APPPATH.'libraries/test_int_full_database.xls';
          $file=APPPATH.'libraries/test_courses.xls';
          $connection = new Spreadsheet_Excel_Reader(); // our main object
          $connection->read($file);

          $startrow_tee = 2;
          $endrow_tee = 17714;
          echo '<pre>';
          for($i=$startrow_tee;$i<=$endrow_tee;$i++){ // we read row to row

                $data = array(
                  'course_id' => (trim($connection->sheets[0]["cells"][$i][1])) ? trim($connection->sheets[0]["cells"][$i][1]) : 0, 
                  'club_id' => (trim($connection->sheets[0]["cells"][$i][2])) ? trim($connection->sheets[0]["cells"][$i][2]) : 0, 
                  'course_name' => (trim($connection->sheets[0]["cells"][$i][3])) ? trim($connection->sheets[0]["cells"][$i][3]) : 0, 
                  'holes' => (trim($connection->sheets[0]["cells"][$i][4])) ? trim($connection->sheets[0]["cells"][$i][4]) : 0, 
                  'par' => (trim($connection->sheets[0]["cells"][$i][5])) ? trim($connection->sheets[0]["cells"][$i][5]) : 0, 
                  'course_type' => (trim($connection->sheets[0]["cells"][$i][6])) ? trim($connection->sheets[0]["cells"][$i][6]) : 0, 
                  'course_architect' => (trim($connection->sheets[0]["cells"][$i][7])) ? trim($connection->sheets[0]["cells"][$i][7]) : 0,
                  'open_date' => (trim($connection->sheets[0]["cells"][$i][8])) ? trim($connection->sheets[0]["cells"][$i][8]) : 0,
                  'guest_policy' => (trim($connection->sheets[0]["cells"][$i][9])) ? trim($connection->sheets[0]["cells"][$i][9]) : 0,
                  'weekday_price' => (trim($connection->sheets[0]["cells"][$i][10])) ? trim($connection->sheets[0]["cells"][$i][10]) : 0,
                  'weekend_price' => (trim($connection->sheets[0]["cells"][$i][11])) ? trim($connection->sheets[0]["cells"][$i][11]) : 0,
                  'twilight_price' => (trim($connection->sheets[0]["cells"][$i][12])) ? trim($connection->sheets[0]["cells"][$i][12]) : 0,
                  'fairway' => (trim($connection->sheets[0]["cells"][$i][13])) ? trim($connection->sheets[0]["cells"][$i][13]) : 0,
                  'green' => (trim($connection->sheets[0]["cells"][$i][14])) ? trim($connection->sheets[0]["cells"][$i][14]) : 0,
                  'currency' => (trim($connection->sheets[0]["cells"][$i][15])) ? trim($connection->sheets[0]["cells"][$i][15]) : 0,
                  'address' => (trim($connection->sheets[0]["cells"][$i][16])) ? trim($connection->sheets[0]["cells"][$i][16]) : 0,
                  'longitude' => (trim($connection->sheets[0]["cells"][$i][17])) ? trim($connection->sheets[0]["cells"][$i][17]) : 0,
                  'latitude' => (trim($connection->sheets[0]["cells"][$i][18])) ? trim($connection->sheets[0]["cells"][$i][18]) : 0
                );
                echo trim($connection->sheets[0]["cells"][$i][1]).'   --'.$i;
                echo '</br>';
                $this->home_model->insertData('course_info',$data);
          }

      }
      
      
      /*New code for uploading courses into database*/
      function courses(){
          // require_once(APPPATH.'libraries/reader.php');
          ini_set('memory_limit', '-1');
          ini_set('max_execution_time', 0);

          $courses_info = $this->home_model->getCourses('course_info');
          // echo "<pre>";
          // print_r($courses_info);die;

          foreach($courses_info as $cs){
            if($cs->holes <= 18){
              $tees_info = $this->home_model->getTees('tee_info',$cs->course_id);
                  if($tees_info){
                    $tee_info = array();
                    foreach($tees_info as $ts){
                        $hole_info = array();
                        for($m=1; $m<=$cs->holes; $m++){
                            $hole_info[] = array(
                              'holeno' => $m, 
                              'par' => $ts->{'hole'.$m.'_par'}, 
                              'handicap' => $ts->{'hole'.$m.'_handicap'}, 
                              'marker_distance' => $ts->{'hole'.$m}, 
                              'state' => 1,
                            );
                          }

                          $tee_info[] = array(
                            'teename' => $ts->tee_name, 
                            'teecolor' => $this->findColorHexValue($ts->tee_color), 
                            'sloperating' => $ts->slope, 
                            'courserating' => $ts->rating, 
                            'state' => 1,
                            'hole_info_arr' => $hole_info
                          );
                    }
                  }
            }
            if(!empty($tees_info)){
              $course_info[] = array(
                            'coursename' => $cs->course_name, 
                            'courseaddress' => $cs->address, 
                            'latitude' => $cs->latitude, 
                            'longitude' => $cs->longitude, 
                            'totalhole' => $cs->holes,
                            'purchase_id' => 'com.view9.'.$cs->course_id,
                            'image' => 'images/golfcourse/golfavatar.png', 
                            'state' => 1, 
                            'tee_info_arr' => $tee_info, 
                          );
                          $this->insertCourses($course_info);
                          $course_info = array();
            }
            
          }

      }

      function insertCourses($course_info){
          $counter = 0;
          if($course_info){
            foreach($course_info as $cs){
                $data_cs_info = array(
                            'coursename' => $cs['coursename'], 
                            'courseaddress' => $cs['courseaddress'], 
                            'latitude' => $cs['latitude'], 
                            'longitude' => $cs['longitude'], 
                            'totalhole' => $cs['totalhole'], 
                            'purchase_id' => $cs['purchase_id'],
                            'image' => 'images/golfcourse/golfavatar.png', 
                            'state' => 1
                          );
                  $insert_course_id = $this->home_model->insertData('coursetable',$data_cs_info);
                  foreach($cs['tee_info_arr'] as $te){
                  echo $cs['purchase_id'].'  --'.$te['teecolor'];
                      $data_tee_info = array(
                              'course_id' => $insert_course_id, 
                              'teename' => $te['teename'], 
                              'teecolor' => $te['teecolor'], 
                              'sloperating' => $te['sloperating'], 
                              'courserating' => $te['courserating'], 
                              'state' => 1,
                            );
                        $insert_teeset_id = $this->home_model->insertData('teeset',$data_tee_info);

                        foreach($te['hole_info_arr'] as $ho){
                            $data_hole_info = array(
                              'teeset_id' => $insert_teeset_id, 
                              'holeno' => $ho['holeno'], 
                              'par' => $ho['par'], 
                              'handicap' => $ho['handicap'], 
                              'marker_distance' => $ho['marker_distance'], 
                              'state' => 1,
                            );
                        $this->home_model->insertData('hole',$data_hole_info);
                        }
                  }
            }
          }
        return true;
      }

  }
  

